# Welcome to Jekyll!
#

# Site settings
title: Multi Disciplinary Solutions
description: |
    When you need to find that which you wished existed, but can't
owner: Carlos Cluff # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: multidisciplinarysolutionsco@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xyz.com" # the base hostname & protocol for your site
social:
  github: https://github.com/carloscluff
  linkedin-square: https://linkedin.com/in/carlos-cluff-8507b8126
  email: /contact/

# Build settings
markdown: kramdown
#sass:
#  style: compressed
